language: node_js
node_js: 8

cache:
  directories:
  - node_modules
  - functions/node_modules

before_deploy:
  - rm -rf public
  - mv build/es6-bundled/public public
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: oDNtxUKsZFUcf+UhDlMtABV0lIomcQFZfpRFuYVrV7brf97IhPxepfQzsNjTgNtNSvIhRw5RLc5qsDMzZoC7FvNjUilWwtlz2gKWxJMFnHM73y3WRGbAswYvpIGSQJ/MNKUYjWlLfiw/a9jaiJ7N6TwaIDZ+sS73ocJ77Hgfb4Y0sMtNXdtBkCi0sLg0/aWKE9+AlX3cVBsyPfW+TQEaGoobi7sNS6UXopHu7krSA+cbGEHJmAVHyzZw8pzDtCI7GMI7vrbVjsFhQh5NHvy49giHLFwid5uHaDV1zckD6896Egh2lFSV3G6Hr9tNtAM/2ss4ohu7bMJWytRgIvdTgF3FYP4QHfgw+Lins7Ug+NmViQzUrgOI3IP1kNiRUbqv4svlyTs3XuArNMw2YhNJAsHRWErY3GFO7RA768Hi4LMwxJaDvx8iPx61I9hJmXCA0kn8WY+d2N2Oz29pO9ZKBIyRWjrsy00oOEIfxEejKD+8kgJJghnH20ZJ7ZHw6z8N6t4V6ZcT8IN0fg1xQ24UkXaewtkSg0Nw7ZpWqPZX+aAcGExOOBspx1Q/zyzqv1DE/qiHBj+tzmkglgbCs4FkDLEDNIUqV3yHj/eWNjGb7ChehMRjQiedOwAxpQHD64BjWayUM3EslwUbJE72RXPuILORyFHbbcD9T2CoCBQWeRA=
  project: techinterop-io
